### ISSUE TITLE
InvalidArgumentExcpetion ?!

### ISSUE THREAD

**Issue by H-i-red** [Pennebaker/craft-architect#1]
![skarmavbild 2018-01-27 kl 16 42 07](https://user-images.githubusercontent.com/19476159/35473687-049e53f2-0384-11e8-856c-ab8d7e9b24f7.png)

**Comment by spAnser** [comment]
This is definitely a weird one. It clearly exists when you try to search for it.

![image](https://user-images.githubusercontent.com/193938/35474042-858bfe96-034e-11e8-97b9-7f48662c9bd1.png)

**Comment by spAnser** [comment]
OK so since this plugin is in beta at the moment since it is not ready for a live environment and is missing a lot of features. You will need to modify your composer.json file to accept beta stability. At this time I cannot recommend it for a production website. However it does create database backups before it does anything and it will delete the backup as long as it succeeded at everything.

```
    "minimum-stability": "beta",
```

**Comment by H-i-red** [comment]
Cool thanks  !!
