### ISSUE TITLE
Allow creating new blocks within a matrix field

### ISSUE THREAD

**Issue by FreekVR** [Pennebaker/craft-architect#13]
I was wondering if it is possible to insert any new block types within a matrix field when that matrix field already exists. Currently it will throw an error and not do anything with the matrix field.

It's quite a common pattern for us to create a single "content" or "page builder" field which will get updated with new blockTypes as development on the project progresses, so it would be a great help if any block types newly added to the field would be allowed to be "merged" into the matrix field. Currently we have to delete the field first, then import it again, so any content attached to the field would be lost.

**Comment by spAnser** [comment]
This is actually something that may come during or after migrations.

There will eventually be an option when importing that allows you to check a box that would perform an update. So that it would update an existing field. That way you could version control the json better since right now it really only helps with the setup.

**Comment by lukebailey** [comment]
This would be a great feature, any ideas on progress?

**Comment by spAnser** [comment]
Finally gotten around to looking into this. It is proving somewhat difficult to update a matrix field. That could be however because I am going about it the wrong way.
